# Generated by Django 3.2.6 on 2021-08-28 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='zip',
            new_name='zipcode',
        ),
    ]
