# Generated by Django 3.2.6 on 2021-09-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customer_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdetails',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (2, 2), (2, 2), (2, 2)], null=True),
        ),
    ]
