# Generated by Django 3.2.6 on 2021-09-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_workdetails_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='rating_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
