# Generated by Django 3.2.6 on 2021-09-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210909_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdetails',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (4, 4)], null=True),
        ),
    ]
