# Generated by Django 3.2.6 on 2021-09-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_workdetails_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workdetails',
            name='verified',
        ),
        migrations.AddField(
            model_name='workdetails',
            name='job_status',
            field=models.CharField(blank=True, choices=[('Unapproved', 'Unapproved'), ('Approved', 'Approved'), ('Closed', 'Closed')], max_length=34, null=True),
        ),
    ]
