# Generated by Django 3.2.6 on 2021-09-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210909_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='rating_count',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
