# Generated by Django 3.2.6 on 2021-09-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_employee_rating_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdetails',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
