# Generated by Django 3.2.6 on 2021-09-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210917_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='adharno',
            field=models.IntegerField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_rating',
            field=models.FloatField(blank=True, max_length=3, null=True),
        ),
    ]
