# Generated by Django 3.2.6 on 2021-09-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210918_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='adharno',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='zipcode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
