# Generated by Django 3.2.6 on 2021-09-18 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210918_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='adharno',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
