# Generated by Django 3.2.6 on 2024-04-08 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_customer_adharno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='adharno',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
